modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="forge_backrooms_plus"
version="0.0.7"
displayName="Forge Backrooms Plus"
displayURL="https://mcreator.net"
credits="Made with MCreator by TygrysGames"
authors="TygrysGames, MCreator"
description="It's possible to escape from Backrooms, isn't it?"

[[dependencies.forge_backrooms_plus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




